Changes in test/ resulting from the audit
sablier-labs/v2-periphery pull request #138
Opened 2023-07-09 11:25 UTC by IaroslavMazur

2023-07-09 11:33 UTC, IaroslavMazur commented
@PaulRBerg, see [this comment](https://github.com/sablier-labs/v2-periphery/pull/139#issuecomment-1627688682) that also relates to this PR

2023-07-10 12:53 UTC, PaulRBerg commented on test/integration/target/burn/burn.t.sol
> +        // Expect the NFT owner to not exist anymore.
😄

2023-07-10 12:53 UTC, PaulRBerg commented on test/integration/target/cancel-multiple/cancelMultiple.t.sol
> +    function cancelMultiple(ISablierV2Lockup lockup, uint256[] memory streamIds) internal {
`test_cancelMultiple` is ok

2023-07-10 12:53 UTC, PaulRBerg commented on test/integration/target/renounce/renounce.t.sol
> +    function renounce(ISablierV2Lockup lockup, uint256 streamId) internal {
`test_Renounce` is ok

2023-07-10 12:54 UTC, PaulRBerg commented on test/integration/target/withdraw-max-and-transfer/withdrawMaxAndTransfer.t.sol
> +    function withdrawMaxAndTransfer(ISablierV2Lockup lockup, uint256 streamId) internal {
`test_WithdrawMaxAndTransfer` is ok

2023-07-10 13:01 UTC, PaulRBerg commented on test/fork/plugin/onStreamCanceled.t.sol
> +/// @dev Runs against the asset passed to its constructor.
Yes, and there are multiple instances of this contract. I'll rewrite the comment to say this:

> Runs against multiple fork assets

2023-07-10 13:02 UTC, PaulRBerg commented on test/Base.t.sol
> +        return abi.decode(input, (uint256[]));
Adding these functions increases the number of lines of code - let's apply the principle of KISS and remove them

2023-07-10 13:07 UTC, PaulRBerg requested changes
Thanks, @IaroslavMazur.

2023-07-10 13:12 UTC, PaulRBerg approved these changes
LGTM now (after my recent commit)

2023-07-10 13:24 UTC, PaulRBerg commented
Merging - fork tests are failing because @IaroslavMazur's fork does not have an `RPC_URL_MAINNET` defined in the GitHub Secrets.

2023-07-10 13:24 UTC, merged

2023-07-10 15:01 UTC, IaroslavMazur commented on test/integration/target/burn/burn.t.sol
> +    function burn(ISablierV2Lockup lockup, uint256 streamId) internal {
Hm... Fair point.

Though, that also speaks to my original concern with the naming: `test_Burn` looks too much like a test that's supposed to be executed by Foundry. The only thing that differentiates it from the ones that do get executed is the `internal` modifier. 😕

2023-07-10 15:07 UTC, IaroslavMazur commented on test/utils/BatchBuilder.sol
> +    function generateBatchFromSample(
Oh... And I was so proud for having come with the whole "sample to batch" framework... 😢

2023-07-10 15:12 UTC, PaulRBerg commented on test/integration/target/burn/burn.t.sol
> +    function burn(ISablierV2Lockup lockup, uint256 streamId) internal {
Acknowledged