feat: add "ProxyTargetPush"
sablier-labs/v2-periphery pull request #173
Opened 2023-08-24 15:00 UTC by PaulRBerg

Closes #172.

2023-08-24 17:46 UTC, andreivladbrg requested changes
In the `expectCallToTransfer` and `expectCallToTransferFrom` from `Base_Test` we have to add:

```solidity
if (target != targetPush) {}
```

We should add the `SablierV2ProxyTargetPush` in the `prepare-artifacts` script. Add a workflow dispatch.

Regarding the naming, I don't think "Push" is the best name, it doesn't really say much. What about "NoTransfer"

2023-08-25 06:37 UTC, PaulRBerg commented
Thanks for the review.

> In the `expectCallToTransfer` and `expectCallToTransferFrom` from `Base_Test` we have to add:

Good catch.

> We should add the `SablierV2ProxyTargetPush` in the `prepare-artifacts` script. Add a workflow dispatch.

Yes.

> Regarding the naming, I don't think "Push" is the best name

It's a good name, actually.

1. [This is how people typically refer to `transfer`-based flows](https://twitter.com/0xM3rlin/status/1686522018785820672).
2. It's a short, succinct name (just one word.

2023-08-25 11:22 UTC, andreivladbrg commented
>It's a good name, actually.
    [This is how people typically refer to transfer-based flows](https://twitter.com/0xM3rlin/status/1686522018785820672).


Ok, fine. It is the first time I hear the word in this context, and maybe that's why it doesn't sounds well with me.

Also, there is one more miss, we should remove `SafeERC20` from the contract: 

https://github.com/sablier-labs/v2-periphery/blob/af807da8d3f634ea72191be29bd23d3fff272dbb/src/SablierV2ProxyTargetPush.sol#L12

2023-08-25 11:25 UTC, andreivladbrg approved these changes

2023-08-25 11:58 UTC, merged