refactor: rename "AirstreamCampaign" to "MerkleStreamer"
sablier-labs/v2-periphery pull request #186
Opened 2023-09-11 09:28 UTC by PaulRBerg

Implements https://github.com/sablier-labs/v2-periphery/discussions/183.

Note that I have kept referring to the total amount as "campaign total amount", and to the expiration as "campaign expiration".

2023-09-15 12:08 UTC, andreivladbrg requested changes
Shouldn't we rename [this dir](https://github.com/sablier-labs/v2-periphery/tree/refactor/rename-airstreams/test/integration/merkle-streamer/campaign-ll) to `ll`

2023-09-15 12:08 UTC, andreivladbrg commented on test/utils/Precompiles.t.sol
> +    function test_DeployMerkleStreamerFactory() external onlyTestOptimizedProfile {
Not alphabetically ordered

2023-09-15 12:08 UTC, andreivladbrg commented on test/utils/Precompiles.t.sol
> +import { ISablierV2MerkleStreamerFactory } from "../../src/interfaces/ISablierV2MerkleStreamerFactory.sol";
Not alphabetically ordered

2023-09-15 12:08 UTC, andreivladbrg commented on test/utils/Precompiles.t.sol
> +            vars.actualMerkleStreamerFactory,
Not alphabetically ordered

2023-09-15 12:08 UTC, andreivladbrg commented on test/integration/merkle-streamer/campaign-ll/claim/claim.tree
> +         ├── it should create a LockupLinear Merkle streamer
Typo: stream

2023-09-15 12:08 UTC, andreivladbrg commented on test/fork/assets/USDT.t.sol
> +import { MerkleStreamerLL_Fork_Test } from "../merkle-streamer/MerkleStreamerLL.t.sol";
Not alphabetically ordered

2023-09-15 12:08 UTC, andreivladbrg commented on test/fork/assets/USDC.t.sol
> +import { MerkleStreamerLL_Fork_Test } from "../merkle-streamer/MerkleStreamerLL.t.sol";
Not alphabetically ordered

2023-09-16 09:26 UTC, PaulRBerg commented
Thanks for the review.

I have accepted all of your proposed changes and merged the other PR.

2023-09-16 09:27 UTC, PaulRBerg commented
Once the CI checks finish, we can squash and merge the PR.

2023-09-17 10:14 UTC, merged