ci: remove etherscan api keys
sablier-labs/v2-periphery pull request #258
Opened 2024-01-10 18:43 UTC by PaulRBerg

Analogous to https://github.com/sablier-labs/v2-core/pull/786.

2024-01-10 18:50 UTC, smol-ninja requested changes
We also have to update [CONTRIBUTING.md](https://github.com/sablier-labs/v2-periphery/blob/ci/remove-etherscan-api-keys/CONTRIBUTING.md#deployment).

2024-01-11 14:24 UTC, andreivladbrg commented on .env.example
>  export RPC_URL_MAINNET="YOUR_RPC_URL_MAINNET"
instead, we core must be updated to alphabetically order them

just pushed a commit: https://github.com/sablier-labs/v2-core/commit/3035b4c4cae35b0713cc3c7627882a7864cde5dc

2024-01-11 14:26 UTC, andreivladbrg approved these changes

2024-01-11 14:41 UTC, smol-ninja approved these changes

2024-01-11 14:47 UTC, merged