refactor: rename Batch to BatchLockup
sablier-labs/v2-periphery pull request #322
Opened 2024-04-11 01:46 UTC by smol-ninja

closes #320

2024-04-11 06:54 UTC, PaulRBerg requested changes
changes requested below

2024-04-11 06:54 UTC, PaulRBerg commented on test/fork/assets/USDC.t.sol
> +import { CreateWithTimestamps_LockupTranched_Batch_Lockup_Fork_Test } from
`BatchLockup` is the name of a single contract so let's remove the underscore between these words.

2024-04-11 06:54 UTC, PaulRBerg commented on test/utils/BatchLockupBuilder.sol
> +    function fillBatchLockup(
Adding  `Lockup` is redundant in these functions. That this is about `BatchLockup` is implied by the name of the library (`BatchLockupBuilder`).

2024-04-11 06:54 UTC, PaulRBerg commented on test/utils/Defaults.sol
> +    function batchLockupCreateWithDurationsLD()
That this is about `Lockup` is implied by `LD`. We can just say `batchCreateWithDurationsLD`, and ditto for the other functions in here.

2024-04-11 06:54 UTC, PaulRBerg commented on test/utils/DeployOptimized.sol
>      /// @notice Deploys all V2 Periphery contracts from a optimized source in the following order:
"an optimized source"

2024-04-11 07:00 UTC, PaulRBerg approved these changes
I have addressed all of my feedback above in the latest commit. LGTM now.

2024-04-11 14:10 UTC, smol-ninja commented
Similar to https://github.com/sablier-labs/v2-periphery/pull/321, I will be re-doing it with `prb-feedback` changes as there are a so many git conflicts.

2024-04-11 16:55 UTC, smol-ninja commented
@PaulRBerg can you please have a quick look to this as well?

2024-04-12 10:22 UTC, smol-ninja commented on test/utils/BatchLockupBuilder.sol
> +        returns (BatchLockup.CreateWithDurationsLD[] memory batchLockup)
Cool. Making changed now.

2024-04-12 11:06 UTC, merged